version: '2.4'

services:
  infra:
    restart: always
    image: philophilo/fire-infra
    build: .
    environment:
      AWS_SECRET_KEY: $AWS_SECRET_KEY
      AWS_ACCESS_KEY: $AWS_ACCESS_KEY
      REGION: $REGION
      KEY: $KEY
      BUCKET: $BUCKET
      BACKEND_IMAGE: $BACKEND_IMAGE
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
      SECRET_KEY: $SECRET_KEY
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_PORT: $EMAIL_PORT
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      NAMESPACE: $NAMESPACE
      PGDATA: $PGDATA
      TLS_CRT: $TLS_CRT
      TLS_KEY: $TLS_KEY
      DOMAIN: $DOMAIN
    volumes:
      - ${PWD}:/app
    stdin_open: true
    tty: true
    container_name: fire-infra
    networks:
      - fire-net

networks:
  fire-net:
    driver: bridge
