---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $NAMESPACE
  name: database-variables
data:
  POSTGRES_USER: $DATABASE_USER
  POSTGRES_PASSWORD: $DATABASE_PASSWORD
  POSTGRES_DB: $DATABASE_NAME
  PGDATA: $PGDATA