---

apiVersion: v1
kind: Service
metadata:
  namespace: $NAMESPACE
  name: db
  labels:
    app: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db
